import './globals.scss'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Sidebar from './Sidebar';
import AuthProvider from './auth/Provider';


const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`w-full h-full ${roboto.className}`}>
          <AuthProvider>
      <body>
        <main className='md:grid md:grid-cols-[200px_1fr] min-h-[100dvh]'>
        <aside className="h-[50px] sm:h-[50px] md:h-full hover:h-full bg-slate-200 md:max-w-sm md:w-full overflow-hidden :hover:translate-x-[200]">
          <Sidebar className="text-red"></Sidebar>
        </aside>
        <div className="col-span-1 p-5">
            {children}
        </div>
        </main>
      </body>
          </AuthProvider>
    </html>
  );
}
