import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './Sidebar';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='w-full h-full'>
      <body className="grid grid-cols-[1px_1fr] md:grid-cols-[200px_1fr] h-full">
        <aside className="bg-slate-200 md:max-w-sm md:w-full overflow-hidden :hover:translate-x-[200]">
          <Sidebar></Sidebar>
        </aside>
        <main className="md:col-span-1 p-5">
          {children}
        </main>
      </body>
    </html>
  );
}
